import { In_Tokyo } from "./yamanote_stations";

test('山手線内回りの整合性テスト', function () {
    expect(In_Tokyo.next.name).toBe("神田")
    expect(In_Tokyo.next.next.name).toBe("秋葉原")
    expect(In_Tokyo.next.next.next.name).toBe("御徒町")
    expect(In_Tokyo.next.next.next.next.name).toBe("上野")
    expect(In_Tokyo.next.next.next.next.next.name).toBe("鶯谷")
    expect(In_Tokyo.next.next.next.next.next.next.name).toBe("日暮里")
    expect(In_Tokyo.next.next.next.next.next.next.next.name).toBe("西日暮里")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.name).toBe("田端")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.name).toBe("駒込")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.name).toBe("巣鴨")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.name).toBe("大塚")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("池袋")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("目白")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("高田馬場")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("新大久保")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("新宿")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("代々木")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("原宿")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("渋谷")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("恵比寿")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("目黒")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("五反田")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("大崎")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("品川")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("高輪ゲートウェイ")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("田町")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("浜松町")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("新橋")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("有楽町")
    expect(In_Tokyo.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.next.name).toBe("東京")
})
